### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by jraff1** [ubuntudesign/www.ubuntu.com#1248]
## Summary

I am searching for a good "ycopy" implementation in some UBUNTU flavor.
I know there are many backup methodologies, but a plain Copy x to y doesn't seem to exist!
I did a search for "backup download" on the main UBUNTU site, got a first page with several uninformative
entries, I tried the NEXT link (https://www.ubuntu.com/search?q=backup%20download&limit=10&offset=10)
and for what ever reason if flunked.
## Process
Tried NEXT link
see above
## Current and expected result
I am still looking for a YCOPY for linux.
## Screenshot

**Comment by pmahnke** [comment]
@nottrobin I suspect there are only the first ten and we aren't dealing with the premature end of the list.

**Comment by nottrobin** [comment]
Normally this issue happens (I think) because one of the search results to be displayed on the results page has special characters in it. I just created [another issue](https://github.com/ubuntudesign/www.ubuntu.com/issues/1263) to look into this. As I believe this is the same issue, I'm going to close this issue now.

With regard to YCOPY, I think perhaps what you want would be covered by [rsync](https://linux.die.net/man/1/rsync)? In any case, we don't tend to discuss generic Linux or Unix utilities on www.ubuntu.com. In future you're better of search or asking on https://askubuntu.com/ or https://unix.stackexchange.com/.
